use_frameworks!

target 'SJSwiftSideMenuController_Example' do
  pod 'SJSwiftSideMenuController', :path => 'https://github.com/sumitjagdev/SJSwiftSideMenuController.git'

  target 'SJSwiftSideMenuController_Tests' do
    inherit! :search_paths

    
  end
end
